# Generated by Django 3.1.4 on 2020-12-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20201219_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='noname', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'timeslot')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
